### ISSUE TITLE
Confused about upgrading from 0.1.3 to 1.0.5 and Grafana 6.7.3 to 8.x

### ISSUE THREAD

**Issue by JCP13** [pierosavi/imageit-migration#2]
Hi,

 Sorry for the dumb question but I am a little confused about the upgrade process. What do I upgrade first, Imageit then Grafana, and use the imageit-migration as instructed?

Thank you.

**Comment by pierosavi** [comment]
First use migration and copy the results somewhere, then upgrade Grafana, then the panel plugin itself and paste the results back into the panels

**Comment by JCP13** [comment]
Great, thank you!
